const CONSTITUTION_CARDS = [
    { article: "Article 1", body: "Name and territory of the Union" },
    { article: "Article 2", body: "Admission or establishment of new States" },
    { article: "Article 3", body: "Formation of new States and alteration of areas, boundaries or names of existing States" },
    { article: "Article 4", body: "Laws made under Articles 2 and 3" },
    { article: "Article 5", body: "Citizenship at the commencement of the Constitution" },
    { article: "Article 6", body: "Rights of citizenship of certain persons who migrated from Pakistan to India" },
    { article: "Article 7", body: "Rights of citizenship of certain migrants to Pakistan" },
    { article: "Article 8", body: "Rights of citizenship of certain persons of Indian origin residing outside India" },
    { article: "Article 9", body: "Persons voluntarily acquiring citizenship of a foreign State not to be citizens" },
    { article: "Article 10", body: "Continuance of the rights of citizenship" },
    { article: "Article 11", body: "Parliament to regulate the right of citizenship by law" },

    { article: "Article 12", body: "Definition of the State" },
    { article: "Article 13", body: "Laws inconsistent with or in derogation of Fundamental Rights" },
    { article: "Article 14", body: "Equality before law and equal protection of laws" },
    { article: "Article 15", body: "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth" },
    { article: "Article 16", body: "Equality of opportunity in matters of public employment" },
    { article: "Article 17", body: "Abolition of Untouchability" },
    { article: "Article 18", body: "Abolition of titles" },
    { article: "Article 19", body: "Protection of six freedoms" },
    { article: "Article 20", body: "Protection in respect of conviction for offences" },
    { article: "Article 21", body: "Protection of life and personal liberty" },
    { article: "Article 21A", body: "Right to education" },
    { article: "Article 22", body: "Protection against arrest and detention" },
    { article: "Article 23", body: "Prohibition of traffic in human beings and forced labour" },
    { article: "Article 24", body: "Prohibition of employment of children below fourteen years in factories, mines or hazardous employment" },
    { article: "Article 25", body: "Freedom of conscience and free profession, practice and propagation of religion" },
    { article: "Article 26", body: "Freedom to manage religious affairs" },
    { article: "Article 27", body: "Freedom from taxation for promotion of a religion" },
    { article: "Article 28", body: "Freedom from attendance at religious instruction or worship in certain educational institutions" },
    { article: "Article 29", body: "Protection of interests of minorities" },
    { article: "Article 30", body: "Right of minorities to establish and administer educational institutions" },

    { article: "Article 31A", body: "Saving of laws providing for acquisition of estates and certain other laws" },
    { article: "Article 31B", body: "Validation of certain Acts and Regulations" },
    { article: "Article 31C", body: "Saving of laws giving effect to certain Directive Principles" },
    { article: "Article 32", body: "Right to Constitutional Remedies" },
    { article: "Article 33", body: "Power of Parliament to modify rights in their application to the Armed Forces etc." },
    { article: "Article 34", body: "Restriction on rights while martial law is in force" },
    { article: "Article 35", body: "Legislation to give effect to this Part" },

    { article: "Article 36", body: "Definition (Directive Principles of State Policy)" },
    { article: "Article 37", body: "Application of the principles contained in this Part" },
    { article: "Article 38", body: "State to secure a social order for the promotion of welfare of the people" },
    { article: "Article 39", body: "Certain principles of policy to be followed by the State" },
    { article: "Article 39A", body: "Equal justice and free legal aid" },
    { article: "Article 40", body: "Organisation of village panchayats" },
    { article: "Article 41", body: "Right to work, to education and to public assistance in certain cases" },
    { article: "Article 42", body: "Provision for just and humane conditions of work and maternity relief" },
    { article: "Article 43", body: "Living wage for workers" },
    { article: "Article 43A", body: "Participation of workers in management of industries" },
    { article: "Article 43B", body: "Promotion of co-operative societies" },
    { article: "Article 44", body: "Uniform Civil Code for the citizens" },
    { article: "Article 45", body: "Early childhood care and education" },
    { article: "Article 46", body: "Promotion of educational and economic interests of Scheduled Castes, Scheduled Tribes and other weaker sections" },
    { article: "Article 47", body: "Duty of the State to raise the level of nutrition and the standard of living and to improve public health" },
    { article: "Article 48", body: "Organisation of agriculture and animal husbandry" },
    { article: "Article 48A", body: "Protection and improvement of environment and safeguarding of forests and wildlife" },
    { article: "Article 49", body: "Protection of monuments and places and objects of national importance" },
    { article: "Article 50", body: "Separation of judiciary from executive" },
    { article: "Article 51", body: "Promotion of international peace and security" }
    ,
    { article: "Article 51A", body: "Fundamental Duties" },

    { article: "Article 52", body: "The President of India" },
    { article: "Article 53", body: "Executive power of the Union" },
    { article: "Article 54", body: "Election of President" },
    { article: "Article 55", body: "Manner of election of President" },
    { article: "Article 56", body: "Term of office of President" },
    { article: "Article 57", body: "Eligibility for re-election" },
    { article: "Article 58", body: "Qualifications for election as President" },
    { article: "Article 59", body: "Conditions of President's office" },
    { article: "Article 60", body: "Oath or affirmation by the President" },
    { article: "Article 61", body: "Procedure for impeachment of the President" },
    { article: "Article 62", body: "Time of holding election to fill vacancy in the office of President" },

    { article: "Article 63", body: "The Vice-President of India" },
    { article: "Article 64", body: "Vice-President to be ex officio Chairman of the Council of States" },
    { article: "Article 65", body: "Vice-President to act as President or discharge his functions during casual vacancies" },
    { article: "Article 66", body: "Election of Vice-President" },
    { article: "Article 67", body: "Term of office of Vice-President" },
    { article: "Article 68", body: "Time of holding election to fill vacancy in the office of Vice-President" },
    { article: "Article 69", body: "Oath or affirmation by the Vice-President" },
    { article: "Article 70", body: "Discharge of President's functions in other contingencies" },
    { article: "Article 71", body: "Matters relating to the election of President or Vice-President" },

    { article: "Article 72", body: "Power of President to grant pardons, reprieves, respites or remissions" },
    { article: "Article 73", body: "Extent of executive power of the Union" },
    { article: "Article 74", body: "Council of Ministers to aid and advise the President" },
    { article: "Article 75", body: "Other provisions as to Ministers" },
    { article: "Article 76", body: "Attorney-General for India" },
    { article: "Article 77", body: "Conduct of business of the Government of India" },
    { article: "Article 78", body: "Duties of Prime Minister with respect to furnishing information to the President" },

    { article: "Article 79", body: "Constitution of Parliament" },
    { article: "Article 80", body: "Composition of the Council of States (Rajya Sabha)" },
    { article: "Article 81", body: "Composition of the House of the People (Lok Sabha)" },
    { article: "Article 82", body: "Readjustment after each Census" },
    { article: "Article 83", body: "Duration of Houses of Parliament" },
    { article: "Article 84", body: "Qualification for membership of Parliament" },
    { article: "Article 85", body: "Sessions of Parliament, prorogation and dissolution" },
    { article: "Article 86", body: "Right of President to address and send messages to Houses" },
    { article: "Article 87", body: "Special address by the President" },
    { article: "Article 88", body: "Rights of Ministers and Attorney-General in Parliament" },

    { article: "Article 89", body: "Chairman and Deputy Chairman of the Council of States" },
    { article: "Article 90", body: "Vacation, resignation and removal of Deputy Chairman" },
    { article: "Article 91", body: "Power of Deputy Chairman or other person to perform duties of Chairman" },
    { article: "Article 92", body: "Chairman or Deputy Chairman not to preside while a resolution for removal is under consideration" },
    { article: "Article 93", body: "Speaker and Deputy Speaker of the House of the People" },
    { article: "Article 94", body: "Vacation, resignation and removal of Speaker and Deputy Speaker" },
    { article: "Article 95", body: "Power of Deputy Speaker or other person to perform duties of Speaker" },
    { article: "Article 96", body: "Speaker or Deputy Speaker not to preside while a resolution for removal is under consideration" },
    { article: "Article 97", body: "Salaries and allowances of Chairman, Deputy Chairman, Speaker and Deputy Speaker" },
    { article: "Article 98", body: "Secretariat of Parliament" },
    { article: "Article 99", body: "Oath or affirmation by members" },
    { article: "Article 100", body: "Voting in Houses, power of Houses to act notwithstanding vacancies and quorum" }
    ,
    { article: "Article 101", body: "Vacation of seats" },
    { article: "Article 102", body: "Disqualifications for membership" },
    { article: "Article 103", body: "Decision on questions as to disqualifications of members" },
    { article: "Article 104", body: "Penalty for sitting and voting before making oath or when not qualified" },
    { article: "Article 105", body: "Powers, privileges and immunities of Parliament and its members" },
    { article: "Article 106", body: "Salaries and allowances of members" },
    { article: "Article 107", body: "Provisions as to introduction and passing of Bills" },
    { article: "Article 108", body: "Joint sitting of both Houses in certain cases" },
    { article: "Article 109", body: "Special procedure in respect of Money Bills" },
    { article: "Article 110", body: "Definition of Money Bills" },
    { article: "Article 111", body: "Assent to Bills" },

    { article: "Article 112", body: "Annual Financial Statement (Union Budget)" },
    { article: "Article 113", body: "Procedure in Parliament with respect to estimates" },
    { article: "Article 114", body: "Appropriation Bills" },
    { article: "Article 115", body: "Supplementary, additional or excess grants" },
    { article: "Article 116", body: "Votes on account, votes of credit and exceptional grants" },
    { article: "Article 117", body: "Special provisions as to Financial Bills" },

    { article: "Article 118", body: "Rules of procedure" },
    { article: "Article 119", body: "Regulation by law of procedure in Parliament in relation to financial business" },
    { article: "Article 120", body: "Language to be used in Parliament" },
    { article: "Article 121", body: "Restriction on discussion in Parliament" },
    { article: "Article 122", body: "Courts not to inquire into proceedings of Parliament" },

    { article: "Article 123", body: "Power of President to promulgate Ordinances" },

    { article: "Article 124", body: "Establishment and constitution of the Supreme Court" },
    { article: "Article 125", body: "Salaries of Judges" },
    { article: "Article 126", body: "Appointment of Acting Chief Justice" },
    { article: "Article 127", body: "Appointment of ad hoc Judges" },
    { article: "Article 128", body: "Attendance of retired Judges at sittings of the Supreme Court" },
    { article: "Article 129", body: "Supreme Court to be a Court of Record" },
    { article: "Article 130", body: "Seat of the Supreme Court" },
    { article: "Article 131", body: "Original jurisdiction of the Supreme Court" },
    { article: "Article 132", body: "Appellate jurisdiction in constitutional cases" },
    { article: "Article 133", body: "Appellate jurisdiction in civil matters" },
    { article: "Article 134", body: "Appellate jurisdiction in criminal matters" },
    { article: "Article 134A", body: "Certificate for appeal to the Supreme Court" },
    { article: "Article 135", body: "Jurisdiction and powers of the Federal Court under existing law" },
    { article: "Article 136", body: "Special Leave Petition (Special Leave to Appeal)" },
    { article: "Article 137", body: "Review of judgments or orders by the Supreme Court" },
    { article: "Article 138", body: "Enlargement of the jurisdiction of the Supreme Court" },
    { article: "Article 139", body: "Conferment on the Supreme Court of powers to issue certain writs" },
    { article: "Article 139A", body: "Transfer of certain cases" },
    { article: "Article 140", body: "Ancillary powers of the Supreme Court" },
    { article: "Article 141", body: "Law declared by the Supreme Court to be binding on all courts" },
    { article: "Article 142", body: "Enforcement of decrees and orders of the Supreme Court and orders as to discovery, etc." },
    { article: "Article 143", body: "Power of President to consult the Supreme Court" },
    { article: "Article 144", body: "Civil and judicial authorities to act in aid of the Supreme Court" },
    { article: "Article 145", body: "Rules of Court" },
    { article: "Article 146", body: "Officers and servants and expenses of the Supreme Court" },
    { article: "Article 147", body: "Interpretation" },

    { article: "Article 148", body: "Comptroller and Auditor-General of India" },
    { article: "Article 149", body: "Duties and powers of the Comptroller and Auditor-General" },
    { article: "Article 150", body: "Form of accounts of the Union and of the States" }
    ,
    { article: "Article 151", body: "Audit reports" },

    { article: "Article 152", body: "Definition (States)" },
    { article: "Article 153", body: "Governors of States" },
    { article: "Article 154", body: "Executive power of the State" },
    { article: "Article 155", body: "Appointment of Governor" },
    { article: "Article 156", body: "Term of office of Governor" },
    { article: "Article 157", body: "Qualifications for appointment as Governor" },
    { article: "Article 158", body: "Conditions of Governor's office" },
    { article: "Article 159", body: "Oath or affirmation by the Governor" },
    { article: "Article 160", body: "Discharge of the functions of the Governor in certain contingencies" },
    { article: "Article 161", body: "Power of Governor to grant pardons, reprieves, etc." },
    { article: "Article 162", body: "Extent of executive power of the State" },

    { article: "Article 163", body: "Council of Ministers to aid and advise the Governor" },
    { article: "Article 164", body: "Other provisions as to Ministers" },
    { article: "Article 165", body: "Advocate-General for the State" },
    { article: "Article 166", body: "Conduct of business of the Government of a State" },
    { article: "Article 167", body: "Duties of Chief Minister regarding furnishing information to Governor" },

    { article: "Article 168", body: "Constitution of Legislatures in States" },
    { article: "Article 169", body: "Abolition or creation of Legislative Councils in States" },
    { article: "Article 170", body: "Composition of Legislative Assemblies" },
    { article: "Article 171", body: "Composition of Legislative Councils" },
    { article: "Article 172", body: "Duration of State Legislatures" },
    { article: "Article 173", body: "Qualification for membership of State Legislature" },
    { article: "Article 174", body: "Sessions, prorogation and dissolution of State Legislature" },
    { article: "Article 175", body: "Right of Governor to address and send messages to the House or Houses" },
    { article: "Article 176", body: "Special address by the Governor" },
    { article: "Article 177", body: "Rights of Ministers and Advocate-General in the House or Houses" },

    { article: "Article 178", body: "Speaker and Deputy Speaker of the Legislative Assembly" },
    { article: "Article 179", body: "Vacation, resignation and removal of Speaker and Deputy Speaker" },
    { article: "Article 180", body: "Power of Deputy Speaker or other person to perform duties of Speaker" },
    { article: "Article 181", body: "Speaker or Deputy Speaker not to preside while a resolution for removal is under consideration" },
    { article: "Article 182", body: "Chairman and Deputy Chairman of the Legislative Council" },
    { article: "Article 183", body: "Vacation, resignation and removal of Chairman and Deputy Chairman" },
    { article: "Article 184", body: "Power of Deputy Chairman or other person to perform duties of Chairman" },
    { article: "Article 185", body: "Chairman or Deputy Chairman not to preside while a resolution for removal is under consideration" },

    { article: "Article 186", body: "Salaries and allowances of Speaker, Deputy Speaker, Chairman and Deputy Chairman" },
    { article: "Article 187", body: "Secretariat of State Legislature" },
    { article: "Article 188", body: "Oath or affirmation by members" },
    { article: "Article 189", body: "Voting in Houses, power to act notwithstanding vacancies and quorum" },

    { article: "Article 190", body: "Vacation of seats" },
    { article: "Article 191", body: "Disqualifications for membership" },
    { article: "Article 192", body: "Decision on questions as to disqualifications of members" },
    { article: "Article 193", body: "Penalty for sitting and voting before making oath or when not qualified" },

    { article: "Article 194", body: "Powers, privileges and immunities of State Legislatures and their members" },
    { article: "Article 195", body: "Salaries and allowances of members" },

    { article: "Article 196", body: "Provisions as to introduction and passing of Bills" },
    { article: "Article 197", body: "Restriction on powers of Legislative Council regarding Bills other than Money Bills" },
    { article: "Article 198", body: "Special procedure in respect of Money Bills" },
    { article: "Article 199", body: "Definition of Money Bills" },
    { article: "Article 200", body: "Assent to Bills" }
    ,
    { article: "Article 201", body: "Bills reserved for consideration" },
    { article: "Article 202", body: "Annual Financial Statement (State Budget)" },
    { article: "Article 203", body: "Procedure in Legislature with respect to estimates" },
    { article: "Article 204", body: "Appropriation Bills" },
    { article: "Article 205", body: "Supplementary, additional or excess grants" },
    { article: "Article 206", body: "Votes on account, votes of credit and exceptional grants" },
    { article: "Article 207", body: "Special provisions as to Financial Bills" },
    { article: "Article 208", body: "Rules of procedure" },
    { article: "Article 209", body: "Regulation by law of procedure in the Legislature in relation to financial business" },
    { article: "Article 210", body: "Language to be used in the Legislature" },
    { article: "Article 211", body: "Restriction on discussion in the Legislature" },
    { article: "Article 212", body: "Courts not to inquire into proceedings of the Legislature" },

    { article: "Article 213", body: "Power of Governor to promulgate Ordinances" },

    { article: "Article 214", body: "High Courts for States" },
    { article: "Article 215", body: "High Courts to be Courts of Record" },
    { article: "Article 216", body: "Constitution of High Courts" },
    { article: "Article 217", body: "Appointment and conditions of the office of a Judge of a High Court" },
    { article: "Article 218", body: "Application of certain provisions relating to Supreme Court Judges to High Court Judges" },
    { article: "Article 219", body: "Oath or affirmation by Judges of High Courts" },
    { article: "Article 220", body: "Restriction on practice after being a permanent Judge" },
    { article: "Article 221", body: "Salaries, etc., of Judges" },
    { article: "Article 222", body: "Transfer of a Judge from one High Court to another" },
    { article: "Article 223", body: "Appointment of Acting Chief Justice" },
    { article: "Article 224", body: "Appointment of additional and acting Judges" },
    { article: "Article 224A", body: "Appointment of retired Judges at sittings of High Courts" },
    { article: "Article 225", body: "Jurisdiction of existing High Courts" },
    { article: "Article 226", body: "Power of High Courts to issue certain writs" },
    { article: "Article 226A", body: "Omitted" },
    { article: "Article 227", body: "Power of superintendence over all courts and tribunals" },
    { article: "Article 228", body: "Transfer of certain cases to High Court" },
    { article: "Article 228A", body: "Omitted" },
    { article: "Article 229", body: "Officers and servants and expenses of High Courts" },
    { article: "Article 230", body: "Extension of jurisdiction of High Courts to Union Territories" },
    { article: "Article 231", body: "Establishment of a common High Court for two or more States" },

    { article: "Article 233", body: "Appointment of District Judges" },
    { article: "Article 233A", body: "Validation of appointments of, and judgments delivered by, certain District Judges" },
    { article: "Article 234", body: "Recruitment of persons other than District Judges to the judicial service" },
    { article: "Article 235", body: "Control over subordinate courts" },
    { article: "Article 236", body: "Interpretation" },
    { article: "Article 237", body: "Application of the provisions of this Chapter to certain class or classes of magistrates" },

    { article: "Article 239", body: "Administration of Union Territories" },
    { article: "Article 239A", body: "Creation of local Legislatures or Council of Ministers for certain Union Territories" },
    { article: "Article 239AA", body: "Special provisions with respect to Delhi" },
    { article: "Article 239AB", body: "Provision in case of failure of constitutional machinery in Delhi" },
    { article: "Article 239B", body: "Power of Administrator to promulgate Ordinances during recess of Legislature" },
    { article: "Article 240", body: "Power of President to make regulations for certain Union Territories" }
    ,
    { article: "Article 241", body: "High Courts for Union Territories" },
    { article: "Article 242", body: "Omitted" },

    { article: "Article 243", body: "Definitions (Panchayats)" },
    { article: "Article 243A", body: "Gram Sabha" },
    { article: "Article 243B", body: "Constitution of Panchayats" },
    { article: "Article 243C", body: "Composition of Panchayats" },
    { article: "Article 243D", body: "Reservation of seats" },
    { article: "Article 243E", body: "Duration of Panchayats" },
    { article: "Article 243F", body: "Disqualifications for membership" },
    { article: "Article 243G", body: "Powers, authority and responsibilities of Panchayats" },
    { article: "Article 243H", body: "Powers to impose taxes and funds of Panchayats" },
    { article: "Article 243I", body: "Constitution of State Finance Commission" },
    { article: "Article 243J", body: "Audit of accounts of Panchayats" },
    { article: "Article 243K", body: "State Election Commission" },
    { article: "Article 243L", body: "Application to Union Territories" },
    { article: "Article 243M", body: "Part not to apply to certain areas" },
    { article: "Article 243N", body: "Continuance of existing laws relating to Panchayats" },
    { article: "Article 243O", body: "Bar to interference by courts in electoral matters" },

    { article: "Article 243P", body: "Definitions (Municipalities)" },
    { article: "Article 243Q", body: "Constitution of Municipalities" },
    { article: "Article 243R", body: "Composition of Municipalities" },
    { article: "Article 243S", body: "Constitution and composition of Wards Committees" },
    { article: "Article 243T", body: "Reservation of seats" },
    { article: "Article 243U", body: "Duration of Municipalities" },
    { article: "Article 243V", body: "Disqualifications for membership" },
    { article: "Article 243W", body: "Powers, authority and responsibilities of Municipalities" },
    { article: "Article 243X", body: "Power to impose taxes by Municipalities" },
    { article: "Article 243Y", body: "Finance Commission" },
    { article: "Article 243Z", body: "Audit of accounts of Municipalities" },
    { article: "Article 243ZA", body: "Elections to the Municipalities" },
    { article: "Article 243ZB", body: "Application to Union Territories" },
    { article: "Article 243ZC", body: "Part not to apply to certain areas" },
    { article: "Article 243ZD", body: "District Planning Committee" },
    { article: "Article 243ZE", body: "Metropolitan Planning Committee" },
    { article: "Article 243ZF", body: "Continuance of existing laws and Municipalities" },
    { article: "Article 243ZG", body: "Bar to interference by courts in electoral matters" },

    { article: "Article 243ZH", body: "Definitions (Co-operative Societies)" },
    { article: "Article 243ZI", body: "Incorporation of co-operative societies" },
    { article: "Article 243ZJ", body: "Number and term of members of board and office bearers" },
    { article: "Article 243ZK", body: "Election of members of board" },
    { article: "Article 243ZL", body: "Supersession and suspension of board" },
    { article: "Article 243ZM", body: "Audit of accounts of co-operative societies" },
    { article: "Article 243ZN", body: "Convening of general body meetings" },
    { article: "Article 243ZO", body: "Right of a member to get information" },
    { article: "Article 243ZP", body: "Returns" },
    { article: "Article 243ZQ", body: "Offences and penalties" },
    { article: "Article 243ZR", body: "Application to multi-State co-operative societies" },
    { article: "Article 243ZS", body: "Application to Union Territories" },
    { article: "Article 243ZT", body: "Continuance of existing laws" }
    ,
    { article: "Article 244", body: "Administration of Scheduled Areas and Tribal Areas" },
    { article: "Article 244A", body: "Formation of an autonomous State comprising certain tribal areas in Assam" },

    { article: "Article 245", body: "Extent of laws made by Parliament and by the Legislatures of States" },
    { article: "Article 246", body: "Subject-matter of laws made by Parliament and by the Legislatures of States" },
    { article: "Article 246A", body: "Special provision with respect to Goods and Services Tax (GST)" },
    { article: "Article 247", body: "Power of Parliament to provide for the establishment of certain additional courts" },
    { article: "Article 248", body: "Residuary powers of legislation" },
    { article: "Article 249", body: "Power of Parliament to legislate with respect to a matter in the State List in the national interest" },
    { article: "Article 250", body: "Power of Parliament to legislate with respect to any matter in the State List if a Proclamation of Emergency is in operation" },
    { article: "Article 251", body: "Inconsistency between laws made by Parliament under Articles 249 and 250 and laws made by State Legislatures" },
    { article: "Article 252", body: "Power of Parliament to legislate for two or more States by consent and adoption of such legislation by any other State" },
    { article: "Article 253", body: "Legislation for giving effect to international agreements" },
    { article: "Article 254", body: "Inconsistency between laws made by Parliament and laws made by the Legislatures of States" },
    { article: "Article 255", body: "Requirements as to recommendations and previous sanctions to be regarded as matters of procedure only" },

    { article: "Article 256", body: "Obligation of States and the Union" },
    { article: "Article 257", body: "Control of the Union over States in certain cases" },
    { article: "Article 257A", body: "Omitted" },
    { article: "Article 258", body: "Power of the Union to confer powers on States in certain cases" },
    { article: "Article 258A", body: "Power of the States to entrust functions to the Union" },
    { article: "Article 259", body: "Omitted" },
    { article: "Article 260", body: "Jurisdiction of the Union in relation to territories outside India" },
    { article: "Article 261", body: "Public acts, records and judicial proceedings" },
    { article: "Article 262", body: "Adjudication of disputes relating to waters of inter-State rivers or river valleys" },
    { article: "Article 263", body: "Inter-State Council" },

    { article: "Article 264", body: "Interpretation (Finance)" },
    { article: "Article 265", body: "Taxes not to be imposed except by authority of law" },
    { article: "Article 266", body: "Consolidated Funds and Public Accounts of India and of the States" },
    { article: "Article 267", body: "Contingency Fund" },
    { article: "Article 268", body: "Duties levied by the Union but collected and appropriated by the States" },
    { article: "Article 269", body: "Taxes levied and collected by the Union but assigned to the States" },
    { article: "Article 269A", body: "Levy and collection of GST in the course of inter-State trade or commerce" },
    { article: "Article 270", body: "Taxes levied and distributed between the Union and the States" },
    { article: "Article 271", body: "Surcharge on certain duties and taxes for purposes of the Union" },
    { article: "Article 272", body: "Omitted" },
    { article: "Article 273", body: "Grants in lieu of export duty on jute and jute products" },
    { article: "Article 274", body: "Prior recommendation of President required for Bills affecting taxation in which States are interested" },
    { article: "Article 275", body: "Grants from the Union to certain States" },
    { article: "Article 276", body: "Taxes on professions, trades, callings and employments" },
    { article: "Article 277", body: "Savings" },
    { article: "Article 278", body: "Omitted" },
    { article: "Article 279", body: "Calculation of net proceeds" },
    { article: "Article 279A", body: "Goods and Services Tax Council" },
    { article: "Article 280", body: "Finance Commission" }
    ,
    { article: "Article 281", body: "Recommendations of the Finance Commission" },
    { article: "Article 282", body: "Expenditure defrayable by the Union or a State out of its revenues" },
    { article: "Article 283", body: "Custody, etc., of Consolidated Funds, Contingency Funds and Public Accounts" },
    { article: "Article 284", body: "Custody of suitors' deposits and other moneys received by public servants and courts" },
    { article: "Article 285", body: "Exemption of Union property from State taxation" },
    { article: "Article 286", body: "Restrictions as to imposition of tax on the sale or purchase of goods" },
    { article: "Article 287", body: "Exemption from taxes on electricity" },
    { article: "Article 288", body: "Exemption from taxation by States in respect of water or electricity in certain cases" },
    { article: "Article 289", body: "Exemption of State property and income from Union taxation" },
    { article: "Article 290", body: "Adjustment in respect of certain expenses and pensions" },
    { article: "Article 290A", body: "Annual payment to certain Devaswom Funds" },
    { article: "Article 291", body: "Omitted" },
    { article: "Article 292", body: "Borrowing by the Government of India" },
    { article: "Article 293", body: "Borrowing by States" },

    { article: "Article 294", body: "Succession to property, assets, rights, liabilities and obligations" },
    { article: "Article 295", body: "Succession to property, assets, rights, liabilities and obligations in other cases" },
    { article: "Article 296", body: "Property accruing by escheat or lapse or as bona vacantia" },
    { article: "Article 297", body: "Things of value within territorial waters or continental shelf and resources of the exclusive economic zone" },
    { article: "Article 298", body: "Power to carry on trade, etc." },
    { article: "Article 299", body: "Contracts" },
    { article: "Article 300", body: "Suits and proceedings" },
    { article: "Article 300A", body: "Persons not to be deprived of property save by authority of law" },

    { article: "Article 301", body: "Freedom of trade, commerce and intercourse" },
    { article: "Article 302", body: "Power of Parliament to impose restrictions on trade, commerce and intercourse" },
    { article: "Article 303", body: "Restrictions on the legislative powers of the Union and of the States with regard to trade and commerce" },
    { article: "Article 304", body: "Restrictions on trade, commerce and intercourse among States" },
    { article: "Article 305", body: "Saving of existing laws and laws providing for State monopolies" },
    { article: "Article 306", body: "Omitted" },
    { article: "Article 307", body: "Authority for carrying out the purposes of Articles 301 to 304" },

    { article: "Article 308", body: "Interpretation (Services under the Union and the States)" },
    { article: "Article 309", body: "Recruitment and conditions of service of persons serving the Union or a State" },
    { article: "Article 310", body: "Tenure of office of persons serving the Union or a State" },
    { article: "Article 311", body: "Dismissal, removal or reduction in rank of persons employed in civil capacities" },
    { article: "Article 312", body: "All India Services" },
    { article: "Article 312A", body: "Power of Parliament to vary or revoke conditions of service of officers of certain services" },
    { article: "Article 313", body: "Transitional provisions" },
    { article: "Article 314", body: "Omitted" },

    { article: "Article 315", body: "Public Service Commissions for the Union and for the States" },
    { article: "Article 316", body: "Appointment and term of office of members" },
    { article: "Article 317", body: "Removal and suspension of a member of a Public Service Commission" },
    { article: "Article 318", body: "Power to make regulations as to conditions of service of members and staff" },
    { article: "Article 319", body: "Prohibition as to holding offices by members on ceasing to be such members" },
    { article: "Article 320", body: "Functions of Public Service Commissions" }
    ,
    { article: "Article 321", body: "Power to extend functions of Public Service Commissions" },
    { article: "Article 322", body: "Expenses of Public Service Commissions" },
    { article: "Article 323", body: "Reports of Public Service Commissions" },

    { article: "Article 323A", body: "Administrative Tribunals" },
    { article: "Article 323B", body: "Tribunals for other matters" },

    { article: "Article 324", body: "Superintendence, direction and control of elections vested in the Election Commission" },
    { article: "Article 325", body: "One general electoral roll and no exclusion on grounds of religion, race, caste or sex" },
    { article: "Article 326", body: "Elections to the House of the People and to the Legislative Assemblies on the basis of adult suffrage" },
    { article: "Article 327", body: "Power of Parliament to make provision with respect to elections" },
    { article: "Article 328", body: "Power of Legislature of a State to make provision with respect to elections" },
    { article: "Article 329", body: "Bar to interference by courts in electoral matters" },
    { article: "Article 329A", body: "Omitted" },

    { article: "Article 330", body: "Reservation of seats for Scheduled Castes and Scheduled Tribes in the House of the People" },
    { article: "Article 331", body: "Omitted" },
    { article: "Article 332", body: "Reservation of seats for Scheduled Castes and Scheduled Tribes in the Legislative Assemblies of the States" },
    { article: "Article 333", body: "Representation of the Anglo-Indian community in the Legislative Assemblies (subject to constitutional amendments)" },
    { article: "Article 334", body: "Reservation of seats and special representation to cease after a specified period (as amended)" },
    { article: "Article 335", body: "Claims of Scheduled Castes and Scheduled Tribes to services and posts" },
    { article: "Article 336", body: "Special provision for Anglo-Indian community in certain services" },
    { article: "Article 337", body: "Special provision with respect to educational grants for the benefit of the Anglo-Indian community" },
    { article: "Article 338", body: "National Commission for Scheduled Castes" },
    { article: "Article 338A", body: "National Commission for Scheduled Tribes" },
    { article: "Article 338B", body: "National Commission for Backward Classes" },
    { article: "Article 339", body: "Control of the Union over the administration of Scheduled Areas and the welfare of Scheduled Tribes" },
    { article: "Article 340", body: "Appointment of a Commission to investigate the conditions of Backward Classes" },
    { article: "Article 341", body: "Scheduled Castes" },
    { article: "Article 342", body: "Scheduled Tribes" },
    { article: "Article 342A", body: "Socially and Educationally Backward Classes" },

    { article: "Article 343", body: "Official language of the Union" },
    { article: "Article 344", body: "Commission and Committee of Parliament on Official Language" },
    { article: "Article 345", body: "Official language or languages of a State" },
    { article: "Article 346", body: "Official language for communication between one State and another or between a State and the Union" },
    { article: "Article 347", body: "Special provision relating to language spoken by a section of the population of a State" },
    { article: "Article 348", body: "Language to be used in the Supreme Court and High Courts and for Acts, Bills, etc." },
    { article: "Article 349", body: "Special procedure for enactment of certain laws relating to language" },
    { article: "Article 350", body: "Language to be used in representations for redress of grievances" },
    { article: "Article 350A", body: "Facilities for instruction in mother tongue at primary stage" },
    { article: "Article 350B", body: "Special Officer for linguistic minorities" }
    ,
    { article: "Article 351", body: "Directive for development of the Hindi language" },

    { article: "Article 352", body: "Proclamation of National Emergency" },
    { article: "Article 353", body: "Effect of Proclamation of Emergency" },
    { article: "Article 354", body: "Application of provisions relating to distribution of revenues while Emergency is in operation" },
    { article: "Article 355", body: "Duty of the Union to protect States against external aggression and internal disturbance" },
    { article: "Article 356", body: "Provisions in case of failure of constitutional machinery in States (President's Rule)" },
    { article: "Article 357", body: "Exercise of legislative powers under Proclamation issued under Article 356" },
    { article: "Article 358", body: "Suspension of provisions of Article 19 during Emergency" },
    { article: "Article 359", body: "Suspension of the enforcement of Fundamental Rights during Emergency" },
    { article: "Article 360", body: "Financial Emergency" },

    { article: "Article 361", body: "Protection of President and Governors" },
    { article: "Article 361A", body: "Protection of publication of proceedings of Parliament and State Legislatures" },
    { article: "Article 361B", body: "Disqualification on ground of defection" },
    { article: "Article 362", body: "Omitted" },
    { article: "Article 363", body: "Bar to interference by courts in disputes arising out of certain treaties, agreements, etc." },
    { article: "Article 363A", body: "Recognition granted to Rulers of Indian States to cease and privy purses abolished" },
    { article: "Article 364", body: "Special provisions as to major ports and aerodromes" },
    { article: "Article 365", body: "Effect of failure to comply with directions given by the Union" },
    { article: "Article 366", body: "Definitions" },
    { article: "Article 367", body: "Interpretation" },

    { article: "Article 368", body: "Power of Parliament to amend the Constitution and procedure therefor" },

    { article: "Article 369", body: "Temporary power of Parliament to make laws with respect to certain matters in the State List" },
    { article: "Article 370", body: "Temporary provisions with respect to the former State of Jammu and Kashmir" },
    { article: "Article 371", body: "Special provision with respect to the States of Maharashtra and Gujarat" },
    { article: "Article 371A", body: "Special provision with respect to the State of Nagaland" },
    { article: "Article 371B", body: "Special provision with respect to the State of Assam" },
    { article: "Article 371C", body: "Special provision with respect to the State of Manipur" },
    { article: "Article 371D", body: "Special provisions with respect to the State of Andhra Pradesh or the State of Telangana" },
    { article: "Article 371E", body: "Establishment of Central University in Andhra Pradesh" },
    { article: "Article 371F", body: "Special provisions with respect to the State of Sikkim" },
    { article: "Article 371G", body: "Special provision with respect to the State of Mizoram" },
    { article: "Article 371H", body: "Special provision with respect to the State of Arunachal Pradesh" },
    { article: "Article 371I", body: "Special provision with respect to the State of Goa" },
    { article: "Article 371J", body: "Special provisions with respect to the Hyderabad-Karnataka region" },

    { article: "Article 372", body: "Continuance in force of existing laws" },
    { article: "Article 372A", body: "Power of the President to adapt laws" },
    { article: "Article 373", body: "Power of President in respect of preventive detention" },
    { article: "Article 374", body: "Provisions as to Judges of the Federal Court and proceedings pending" },
    { article: "Article 375", body: "Courts, authorities and officers to continue to function" },
    { article: "Article 376", body: "Provisions as to Judges of High Courts" },
    { article: "Article 377", body: "Provisions as to Comptroller and Auditor-General" },
    { article: "Article 378", body: "Provisions as to Public Service Commissions" },
    { article: "Article 378A", body: "Special provision regarding the Andhra Pradesh Legislative Assembly" },
    { article: "Article 379", body: "Omitted" },
    { article: "Article 380", body: "Omitted" },
    { article: "Article 381", body: "Omitted" },
    { article: "Article 382", body: "Omitted" },
    { article: "Article 383", body: "Omitted" },
    { article: "Article 384", body: "Omitted" },
    { article: "Article 385", body: "Omitted" },
    { article: "Article 386", body: "Omitted" },
    { article: "Article 387", body: "Omitted" },
    { article: "Article 388", body: "Omitted" },
    { article: "Article 389", body: "Omitted" },
    { article: "Article 390", body: "Omitted" },
    { article: "Article 391", body: "Omitted" },
    { article: "Article 392", body: "Power of the President to remove difficulties" },
    { article: "Article 393", body: "Short title" },
    { article: "Article 394", body: "Commencement" },
    { article: "Article 394A", body: "Authoritative text in Hindi" },
    { article: "Article 395", body: "Repeals" }
    ];
